#+TITLE: Econ202B Midterm Study Guide
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: \usepackage[margin=.5in]{geometry}
#+LATEX_HEADER: \usepackage{hyperref} 
#+LATEX_HEADER: \usepackage[dvipsnames]{xcolor}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \newtheorem*{definition}{Definition}
#+LATEX_HEADER: \newtheorem*{example}{Example}
#+LATEX_HEADER: \newtheorem*{theorem}{Theorem}
#+LATEX_HEADER: \newtheorem*{corollary}{Corollary}
#+LATEX_HEADER: \newtheorem*{exercise}{Exercise}
#+LATEX_HEADER: \newtheorem*{problem}{Problem}
#+LATEX_HEADER: \newtheorem*{lemma}{Lemma}
#+LATEX_HEADER: \newtheorem{question}{Question}
#+LATEX_HEADER: \newcommand{\gr}{\textcolor{ForestGreen}}
#+LATEX_HEADER: \newcommand{\rd}{\textcolor{red}}
#+LATEX_HEADER: \newcommand{\R}{\mathbb{R}}
#+LATEX_HEADER: \newcommand{\p}{\mathbb{P}}
#+LATEX_HEADER: \newcommand{\E}{\mathbb{E}}
#+LATEX_HEADER: \newcommand{\frall}{\ \forall}
#+LATEX_HEADER: \newcommand{\st}{_{s_t}}
#+LATEX_HEADER: \newcommand{\var}{\operatorname{Var}}
#+LATEX_HEADER: \newcommand{\cov}{\operatorname{Cov}}
#+LATEX_HEADER: \newcommand{\cor}{\operatorname{Cor}}
#+OPTIONS:  ':t

\newpage

* Search (McCall Model and variants)
  Some facts to keep in mind, in case they come up as parts of questions:
\begin{enumerate}
\item The McCall model is a partial equilibrium model---the distribution of wages is given exogenously. Variants of the model endogenize wages by taking into account firms' wage setting mechanisms.
\end{enumerate}

** McCall Model
Our worker is risk-neutral and infinitely lived, with discount factor $\beta \in (0, 1)$. He maximizes the expected present value of his consumption stream,
\[
\E\left[\sum^\infty_{t = 0} \beta^t c_t\right].
\]
In each period, the worker is either employed (``E'') or unemployed (``U''). If employed, he loses his job with probability $\delta \in (0, 1)$. If unemployed, he receives unemployment benefit $b > 0$ and receives a job offer with probability $\lambda$. *Note*: These parameters are pretty comfortable and can be adjusted to make the problem more complicated, e.g. unemployment benefits decline with unemployment duration, or the probability of finding a new job declines with unemployment duration, etc. In the baseline model, the worker can only search for a new job if he is unemployed, so there is no on-the-job search. If the worker gets an offer, it comes with a wage $w$ that is drawn from a distribution with CDF $F(w)$ over support $[0, \overline{w}]$, where $\overline{w}> b$. If an unemployed worker accepts a job offer, he is employed next period. If he does not receive an offer or if he rejects an offer, he is unemployed next period.

*** Worker's Problem
The worker can be either unemployed or employed, so we will need two Bellman equations. The value of being employed is a function of wages, but the value of being unemployed doesn't. Formally, Bellman equations for the worker's problem are

\begin{align}
V_U &= \underbrace{b}_{\mathclap{\text{flow income}}} + \beta \overbrace{\left[\lambda \int^{\overline{w}}_0 \max \{V_E (w), V_U\} dF(w) + (1 - \lambda) V_U\right]}^{\text{continuation value}}\\
V_E(w) &= w + \beta [(1 - \delta)V_E(w) + \delta V_U]\notag\\
&= \frac{w + \beta \delta V_U}{1 - \beta(1-\delta)}\\
\intertext{Now, we can substitute this expression into the Bellman equation for $V_U$,}
V_U &= b + \beta \lambda \int^{\overline{w}}_0 \max \left\{\frac{w + \beta \delta V_U}{1 - \beta (1 - \delta)}, V_U\right\}dF(w) + \beta (1 - \lambda) V_U\\
\intertext{moving $\beta \lambda V_U$ out of the integral, we get}
&= b + \beta \lambda \int^{\overline{w}}_0 \max \left\{\frac{w - (1 - \beta)V_U}{1 - \beta (1 - \delta)}, 0\right\}dF(w) + \beta V_U.\\
\intertext{We can rearrange this equation to get}
(1 - \beta)V_U &= b + \frac{\beta \lambda}{1 - \beta(1 - \delta)}\int^{\overline{w}}_0 \max \{w - (1 - \beta)V_U, 0\}dF(w).
\intertext{This equation shows that we can use a reservation wage to characterize the worker's behavior; he will accept any wage greater than $(1 - \beta)V_U$.}
\end{align}

*** \rd{Review Integration by Parts!!!}
    
* Diamond, Mortensen and Pissarides

Our focus now is less on workers and when they accept and reject job offers; instead we're studying firms' decision to create jobs in response to labor market conditions. Time is discrete and infinite, $t \in \{0, 1, \ldots \}$. There is a measure one continuum of infinitely lived workers with discount factor $\beta \in (0, 1)$. Workers can either be employed (``E'') or unemployed (``U''). Employed workers are paid wage $w$,and unemployed workers receive unemployment benefit $z$. Firms are identical and can hire workers to produce $y > z$. To hire a worker, firms must post a job at cost $c$ per period. There is a large number of firms that can enter the market; this gives us the free entry condition for the value of posting a job that helps us solve the model. After a job is filled, separation occurs with probability $\delta \in (0, 1)$. In words, workers can be fired, but in the baseline model firing is totally random and occurs with a fixed probability.

Firms that post jobs and unemployed workers meet in the labor market. Instead of providing a micro-founded matching process for unemployed workers and firms, we'll outline a set of reasonable properties that this matching function should fulfill, and then we'll use that arbitrary process to solve the model. Formally, the aggregate number of matches between workers and firms is given by $M(u, v)$, where $u \in [0, 1]$ is the number of unemployed workers and $v \ge 0$ is the number of posted vacancies. We make four assumptions about $M(u, v)$:
\begin{enumerate}
\item Imperfect matching: $M(u, v) \le \min (u, v)$, with a strict inequality if $u > 0$ and $v > 0$.
\item Increasing in $(u, v)$
\item Constant returns to scale: $M(\lambda u, \lambda v) = \lambda M(u, v) \ \forall \lambda > 0$.
\item $M(u, v)$ is concave in $(u, v)$.
\end{enumerate}
We can manipulate our matching function and introduce additional notation to get at some economically meaningful parameters. If we assume that all vacancies have the same matching probability, then
\[
\text{vacancy match probability } = \text{ job filling rate } = \frac{M(u, v)}{v} = M \left[1, \left(\frac{u}{v}\right)^{-1}\right] = q(\theta).
\]
We've introduced a new term, $\theta \equiv$ \gr{labor market tightness}. We can use this same notation to define the matching probability for an unemployed worker,

\[
\text{ worker match probability } = \text{ job finding rate } = \frac{M(u, v)}{u} = \frac{M(u, v)}{v} \frac{v}{u} = \theta q(\theta).
\]
Now let's define an equilibrium for this model. We'll start by defining the law of motion for unemployment. Then, we'll define Bellman equations for our four agents (unemployed workers, employed workers, firms with workers, and firms looking for workers). 

** Unemployment Dynamics
Take market tightness, $\theta$, as given. Each period, a fraction $\delta$ of the employed workers transition to the unemployed state, and a fraction $\theta q(\theta)$ of the unemployed workers transition to the employed state. 
\begin{align*} 
\intertext{The law of motion for the unemployment rate is}
u(t + 1) &= [1 - \theta q(\theta)] u(t) + \delta [1 - u(t)].\\
\intertext{In steady state, the number of hires is equal to the number of separations,}
\theta q(\theta) u &= \delta (1 - u)\\
\implies u^\ast &= \frac{\delta}{\theta q(\theta) + \delta}. \tag{Steady State Unemployment}
\end{align*} 
Note that our law of motion for unemployment always holds, but this $u^\ast$ value only holds once we've reached a steady state.

** Value Functions
Let $V_U$ denote the value to a worker in the unemployed state, $V_E$ the value to a worker in the employed state, $\Pi_V$ the value to a firm that is posting a vacancy, and $\Pi_F$ the value to a firm that has hired a worker (filled a vacancy). These values satisfy the Bellman equations
\begin{align}
V_U &= z + \beta [\theta q(\theta) V_E + (1 - \theta q(\theta))V_U]\\
V_E &= w + \beta [\delta V_U + (1 - \delta)V_E]\\
\Pi_V &= -c + \beta [q(\theta) \Pi_F + (1 - q(\theta))\Pi_V]\\
\Pi_F &= y - w + \beta[\delta \Pi_V + (1 - \delta) \Pi_F].
\end{align}

** Wages
Consider the value to a firm and a worker of some wage $\tilde{w}$,
\begin{align*}
V_E(\tilde{w}) &= \tilde{w} + \beta [\delta V_U + (1 - \delta) V_E]\\
\Pi_F(\tilde{w}) &= y - \tilde{w} + \beta [\delta \Pi_V + (1 - \delta) \Pi_F].\\
\intertext{The net value to the worker and the firm of starting employment is}
V_E(\tilde{w}) - V_U &= \frac{\tilde{w} - (1 - \beta) V_U}{1 - \beta (1 - \delta)}\\
\Pi_F (\tilde{w}) - \Pi_V &= \frac{y - \tilde{w} - (1 - \beta) \Pi_V}{1 - \beta (1 - \delta)}.
\end{align*}
We're going to introduce some new notation and a lemma to summarize when firms and workers actually want to enter into an employment contract, and then we'll talk about how they determine an actual wage once they've decided to enter into a contract.
\begin{lemma}
There exists some wage $\tilde{w}$ such that $V_E(\tilde{w}) - V_U \ge 0$ and $\Pi_F(\tilde{w}) - \Pi_V \ge 0$ if and only if 
\[
\Sigma = V_E(\tilde{w}) - V_U + \Pi_F(\tilde{w}) - \Pi_V = \frac{y - (1 - \beta)(V_U + \Pi_V)}{1 - \beta (1 - \delta)} \ge 0. \tag{Surplus Equation}
\]
\end{lemma}
The Lemma states that the firm and the worker find it optimal to form a relationship if and only if the output per period, $y$, is greater than the annuitized outside value of search, $(1 - \beta) (V_U + \Pi_V)$. This surplus condition pins down a bargaining set, $[\underline{w}, \overline{w}]$. The lower bound is the lowest wage the worker is willing to accept, $\underline{w} = (1 - \beta) V_U$, and the upper bound is the highest wage the firm is willing to pay, $y - (1 - \beta) \Pi_V$. To pin down the actual wage, we need to assume that workers and firms split the surplus according to some rule. For this part of the model, we assume some exogenous baragining power $\phi \in [0, 1]$, which lets us solve for the equilibrium wage as
\[
V_E(w) - V_U &= \phi[V_E + \Pi_F - V_U - \Pi_V] = \phi \Sigma. \tag{equilibrium wages}
\]

** Free Entry
   Since we've assumed that there are many firms that *could* post vacancies, the free entry condition implies that
\[
\Pi_V = 0. \tag{free entry}
\]

\begin{definition}[Search and Matching Equilibrium]
A search and matching equilibrium consists of $(V_E, V_U, \Pi_F, \Pi_V, w, \theta, u)$ that solve the system of equations I labeled.
\end{definition}

** Solving DMP recursively
   \begin{align*}
\intertext{Starting with the free entry condition, $\Pi_V = 0$, we can solve for the surplus as}
\Sigma &= y - z + \beta (1 - \delta) \Pi_F + \beta (1 - \delta - \theta q(\theta)) (V_E - V_U)\\
&= y - z - \beta [1 - \delta - \theta q(\theta) \phi] \Sigma\\
&= \frac{y - z}{1 - \beta + \beta[\delta + \theta q(\theta) \phi]}.\\
\intertext{With the surplus sharing equation and the Bellman equation for a vacancy, we have}
\Pi_V &= -c + \beta q(\theta) (1 -\phi)\Sigma.\\
\intertext{Plugging in $\Pi_V = 0$ from the free entry condition and our expression for $\Sigma$ yields}
c &= (y - z) \frac{\beta q(\theta) (1 - \phi)}{1 - \beta[1 - \delta - \theta q(\theta) \phi]}.\\
\intertext{As long as}
c &< (y - z) \frac{\beta (1 - \phi)}{1 - \beta (1 - \delta)},\\
\intertext{there is a unique equilibrium with entry. The equilibrium value of $\theta$ is decreasing in $(c, z, \delta, \phi)$ and increasing in $(y, \beta)$.}
   \end{align*}
   
* Complete Markets and Asset Pricing

Things I should be able to do (in order, from PS4: \rd{come back and fill in algorithms for finding these objects}):

** Agents' problems in time-zero markets
For this exercise, we take prices as given and try to maximize utility, given a feasibility constraint and non-negativity constraints.
\begin{align*}
\max_{\{c_t (s^t)\}_{t \ge 0, s^t \in S^t}} & \sum_{t \ge 0} \sum_{s^t \in S^t} \beta^t \pi_t (s^t) u (c_t(s^t))\\
\text{s.t. } & \sum_{t \ge 0} \sum_{s^t \in S^t} q_{0t} (c_t (s^t) - y_t (s^t)) \le 0\\
c_t (s^t) &\ge 0 \ \forall t \ge 0, s^t \in S^t
\end{align*}
In more complicated cases we'll adjust the budget constraint and add market clearing constraints, along with a transversality condition for the agent.

** Equilibrium in Time Zero Markets
An equilibrium in time-zero markets has two components:
\begin{enumerate}
\item A sequence for consumption $\{c_t (s^t) \mid t \ge0, s^t \in S^t\}$\\
\item A price system $\{q_{0t} (s^t) \ge 0 \mid t \ge 0, s^t \in S^t\}$
\end{enumerate}
These two objects constitute an equilibrium if the allocation solves the agent's problem given the price system, and all markets (or $L - 1$ markets) clear.

** Calculating equilibrium prices in time-zero markets
\begin{align*}
\beta^t \pi_t (s^t) u'(c_t(s^t)) &= \lambda q_{0t} \tag{agent's FOC}\\
\intertext{Now we can try plugging in a market clearing constraint, in this case $c_t = y_t$,}
\beta^t \pi_t (s^t) u' (y_t (s^t)) &= q_{0t}\\
\intertext{Now just plug in the functional form we have for $u'$.}
\end{align*}
** Calculating equilibrium prices of Arrow securities
\begin{align*}
\intertext{The FOC with respect to Arrow securities gives}
\lambda_{t + 1} (s^t, s_{t + 1} &= Q_{t + 1} (s_{t + 1} \mid s^t) \lambda_t (s^t)\\
\intertext{and the FOC with respect to consumption gives}
\beta^t \pi_t (s^t) u' (c_t (s^t)) &= \lambda_t (s^t).\\
\intertext{We can combine these two expressions to get}
Q_{t + 1} (s_{t + 1} \mid s^t) \frac{\beta^{t + 1 }\pi_{t + 1} (s^{t +1}) u'(c_{t + 1}(s^{t + 1}))}{\beta^t \pi_t (s^t) u' (c_t (s^t))}
\end{align*}
From here we should be able to use an assumption about $\pi$, a market clearing condition to substitute for $c_t$, and a functional form for utility to get a pretty nice expression.
