#+TITLE: Econ201B Midterm Review
#+AUTHOR: Chris Ackerman
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{hyperref} 
#+LATEX_HEADER: \usepackage[dvipsnames]{xcolor}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \newtheorem*{definition}{Definition}
#+LATEX_HEADER: \newtheorem*{example}{Example}
#+LATEX_HEADER: \newtheorem*{theorem}{Theorem}
#+LATEX_HEADER: \newtheorem*{corollary}{Corollary}
#+LATEX_HEADER: \newtheorem*{exercise}{Exercise}
#+LATEX_HEADER: \newtheorem*{problem}{Problem}
#+LATEX_HEADER: \newtheorem{question}{Question}
#+LATEX_HEADER: \newcommand{\gr}{\textcolor{ForestGreen}}
#+LATEX_HEADER: \newcommand{\rd}{\textcolor{red}}
#+LATEX_HEADER: \newcommand{\R}{\mathbb{R}}
#+LATEX_HEADER: \newcommand{\p}{\mathbb{P}}
#+LATEX_HEADER: \newcommand{\E}{\mathbb{E}}
#+LATEX_HEADER: \newcommand{\frall}{\ \forall}
#+LATEX_HEADER: \newcommand{\st}{_{s_t}}
#+LATEX_HEADER: \newcommand{\var}{\operatorname{Var}}
#+LATEX_HEADER: \newcommand{\cov}{\operatorname{Cov}}
#+LATEX_HEADER: \newcommand{\cor}{\operatorname{Cor}}
#+OPTIONS:  ':t

\newpage

* Question 18.5
Example 18.4 (A war of attrition) Two players are involved in a dispute over an object. The value of the object to player $i$ is $v_i > 0$. Time
is modeled as a continuous variable that starts at $0$ and runs indefinitely.
Each player chooses when to concede the object to the other player; if
the first player to concede does so at time $t$, the other player obtains the
object at that time. If both players concede simultaneously, the object
is split equally between them, player $i$ receiving a payoff of $v_i/2$. Time
is valuable: until the first concession each player loses one unit of payoff
per unit of time.

** Exercise 18.5
Formulate this situation as a strategic game and show
that in all Nash equilibria one of the players concedes immediately.


Suppose there is a Nash equilibrium where one player doesn't concede immediately. There are three possible cases for how the game ends:

\begin{enumerate}
\item Player one concedes at time $t > 0$.
\item Player two concedes at time $t > 0$.
\item Both players concede at the same time.
\end{enumerate}

Because the game is symmetric ($v_i$ isn't the same for both players, but it won't actually enter our analysis, and the fact that $v_i > 0$ is all that matters) cases 1--2 are the same. Let's start with case (3). The payoff from conceding at time $t$ is $v_i/2 - t$, but there is a profitable deviation to time $t' = t + \varepsilon$. If player $i$ waits just a *little* bit longer, their payoff becomes $v_i - (t + \varepsilon)$, since they no longer need to split the prize. Since time is continuous we can always find a $\varepsilon$ such that $v_i/2 > \varepsilon$.


Now look at case 1. Player $1$'s payoff is $-t$. Consider a deviation to $t' = t - \varepsilon$. The payoff from this action is $- (t - \varepsilon)$, which is larger than $-t$ and thus a profitable deviation. This same reasoning applies at all $t >0$, hence cases 1--2 cannot be Nash equilibria.

\newpage

* Exercise 56.4 
(Cournot duopoly) Consider the strategic game $\langle \{1, 2\},
(A_i), (u_i)\langle$ in which $A_i = [0, 1]$ and $u_i(a_1, a_2) = a_i(1 - a_1 - a_2)$ for $i = 1,
2$. Show that each player’s only rationalizable action is his unique Nash
equilibrium action.


First let's find the Nash equilibria for practice.

\begin{align*}
u_i &= a_i(1 - a_i - a_{-i})\\
&= a_i - a_i^2 - a_i a_{-i}\\
\intertext{Taking FOCs, we have the optimal behavior for player $i$ given by}
\frac{\partial u_i}{\partial a_i} &= 1 - 2 a_i - a_{-i}\\
&= 0\\
\implies 1 - 2a_1 - a_2 &= 1 - 2a_2 - a_1\\
\implies a_1 &= a_2 \\
&= 1/3
\end{align*}
This question is basically asking us to find this same solution a different way. We're going to exploit the idea that everyone is rational, everyone knows everyone is rational, etc. and then iterate through that argument. To show that behavior is rationalizable, we need to show that there is some $a_{-i}$ for which that behavior is a best response. We know from the question's setup that $a_i \in [0, 1] \forall i$, so we'll exploit that as our first case.
\begin{align*}
0 &= 1 - 2a_i - a_{-i}; \quad a_{-i} \in [0,1]\\
a_{-i} = 0 &\implies a_i = 1/2\\
a_{_i} = 1 &\implies a_i = 0\\
\intertext{This reasoning implies that only actions in the interval $[0, 1/2]$ are rationalizable for each agent. But they both know that, so if they know this is the only region where the other player will act, what are their rationalizable actions now? Let's repeat the same exercise with $a_{-i} \in [0, 1/2]$.} 
a_{-i} = 0 &\implies a_i = 1/2\\
a_{_i} = 1/2 &\implies a_i = 1/4\\
\intertext{Our new interval is $a_i \in [1/4, 1/2]$. Let's go one more time.}
a_{-i} = 1/4 &\implies a_i = 3/8\\
a_{_i} = 1/2 &\implies a_i = 1/4\\
\intertext{If we keep doing this, we'll find that the set of rationalizable actions shrinks to $a_i \in \{1/3\}$, which is what we wanted to show. For a more formal proof, define the endpoints of the set of rationalizable actions as functions of $k$, where $k$ is the number of iterations, and sent $k$ to infinity to show that both the upper bound and lower bound converge to $1/3$ (formalism omitted owing to my laziness).}
\end{align*}
